{{- if .Values.streamer.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-streamer
  labels:
    {{- include "flussonic-watcher-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: streamer
  selector:
    app: {{ .Release.Name }}-streamer
---
apiVersion: media.flussonic.com/v1alpha1
kind: MediaServer
metadata:
  labels:
  name: {{ .Release.Name }}
spec:
  image: flussonic/flussonic:v24.02-107
  hostPort: 85
  adminHostPort: 86
  env:
    - name: LICENSE_KEY
      valueFrom:
        secretKeyRef:
          name: flussonic-license
          key: license_key
          optional: false
    - name: FLUSSONIC_CONFIG_EXTERNAL
      value: "http://apikey0@{{ .Release.Name }}-central2.{{ $.Release.Namespace }}.svc.cluster.local/central/api/v3/streamers/$(FLUSSONIC_HOSTNAME)"
    - name: FLUSSONIC_EDIT_AUTH
      valueFrom:
        secretKeyRef:
          name: flussonic-license
          key: edit_auth
          optional: false
  nodeSelector:
    flussonic.com/streamer: "true"
  configExtra:
    watcher.conf: |
      cluster_key steamerSecretKey0;
      dvr watcher {
        root /storage;
      }
      auth_backend vsaas {
        allow token npIBeaDH6uTkR2;
        backend http://{{ .Release.Name }}-watcher-web.{{ $.Release.Namespace }}.svc.cluster.local/vsaas/api/camera_auth;
      }
  volumes:
  - name: storage
    mountPath: /storage
    hostPath:
      path: /watcher/storage
      type: Directory
{{- end }}
