{{- if .Values.central.create -}}
apiVersion: media.flussonic.com/v1alpha1
kind: Central
metadata:
  name: {{ .Release.Name }}-central
spec:
  database: "postgresql://test:test@{{ .Release.Name }}-postgres.{{ $.Release.Namespace }}.svc.cluster.local:5432/test_c"
  image: "{{ .Values.central.repository }}:{{ .Values.central.tag }}"
  apiKey: "apikey0"
  logRequests: false
  apiUrl: "http://apikey0@{{ .Release.Name }}-central.{{ $.Release.Namespace }}.svc.cluster.local"
  provisionerClusterKey: "steamerSecretKey0"
  provisionerSelector: {{ .Release.Name }}-streamer
  dynamicStreamsAuthToken: "npIBeaDH6uTkR2"
  env:
    - name: CENTRAL_LICENSE_KEY
      valueFrom:
        secretKeyRef:
          name: flussonic-license
          key: license_key
          optional: false
    - name: CENTRAL_UPSTREAM_URL
      value: "http://{{ .Release.Name }}.{{ $.Release.Namespace }}.svc.cluster.local/vsaas/api/camera_auth"
{{- end }}
