{{- if .Values.watcher.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flussonic-watcher-chart.fullname" . }}
  labels:
    {{- include "flussonic-watcher-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 9015
    name: watcher
  selector:
    app: {{ include "flussonic-watcher-chart.fullname" . }}-web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "flussonic-watcher-chart.fullname" . }}-web
spec:
  serviceName: {{ include "flussonic-watcher-chart.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "flussonic-watcher-chart.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "flussonic-watcher-chart.fullname" . }}-web
    spec:
      containers:
      - name: watcher
        image: "{{ .Values.watcher.repository }}:{{ .Values.watcher.tag }}"
        env:
        - name: DB
          value: postgresql://test:test@{{ include "flussonic-watcher-chart.fullname" . }}-postgres.default.svc.cluster.local:5432/test_c
        - name: REDIS
          value: redis://{{ include "flussonic-watcher-chart.fullname" . }}-redis.default.svc.cluster.local:9017
        - name: CENTRAL_URL
          value: http://apikey0@{{ include "flussonic-watcher-chart.fullname" . }}-central.default.svc.cluster.local/streamer/api/v3
        - name: PORT
          value: "9015"
        - name: LISTEN_HOST
          value: '0.0.0.0'
{{- end }}
