apiVersion: media.flussonic.com/v1alpha1
kind: Watcher
metadata:
  name: {{ .Release.Name }}-watcher
spec:
  central: "http://apikey0@{{ .Release.Name }}-central.{{ $.Release.Namespace }}.svc.cluster.local/streamer/api/v3"
  database: "postgresql://test:test@{{ .Release.Name }}-postgres.{{ $.Release.Namespace }}.svc.cluster.local:5432/test_c"
  image: "{{ .Values.watcher.repository }}:{{ .Values.watcher.tag }}"
  env:
    {{- if .Values.watcher.debug }}
    - name: LOG
      value: DEBUG
    - name: ENV
      value: debug
    {{- end }}
    - name: LICENSE_KEY
      valueFrom:
        secretKeyRef:
          name: flussonic-license
          key: license_key
          optional: false
    - name: WATCHER_ADMIN_LOGIN
      valueFrom:
        secretKeyRef:
          name: flussonic-license
          key: login
          optional: false
    - name: WATCHER_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: flussonic-license
          key: pass
          optional: false
