{{- if .Values.ingress.enabled -}}
{{- $fullName := include "flussonic-watcher-chart.fullname" . -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "flussonic-watcher-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  defaultBackend:
    service:
      name: {{ include "flussonic-watcher-chart.fullname" . }}-streamer
      port:
        number: 80
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: {{ include "flussonic-watcher-chart.fullname" . }}
                port:
                  number: 80
          - path: /central
            pathType: Prefix
            backend:
              service:
                name: {{ include "flussonic-watcher-chart.fullname" . }}-central
                port:
                  number: 80
          - path: /vsaas
            pathType: Prefix
            backend:
              service:
                name: {{ include "flussonic-watcher-chart.fullname" . }}
                port:
                  number: 80
          - path: /watcher
            pathType: Prefix
            backend:
              service:
                name: {{ include "flussonic-watcher-chart.fullname" . }}
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flussonic-watcher-chart.fullname" . }}-streamer
                port:
                  number: 80
{{- end }}
